#!/bin/bash

## Description: Run phpcbf
## Usage: phpcbf
## Example: "ddev phpcbf"

set -e

phpcbf --ignore="*.md,*.css, node_modules" --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml /var/www/html/web/modules/custom/$1
