#!/bin/bash

## Description: Run phpstan
## Usage: phpstan
## Example: "ddev phpstan"

# Abort if anything fails
set -e

phpstan analyse web/modules/custom/$1 --no-interaction  -c web/modules/custom/$1/phpstan.neon --memory-limit=-1
